### PR TITLE
jsonp callback support

### PR DESCRIPTION
**Pull request by zzolo**
The following pull request adds callback support.  Keep in mind that my Python skills are not that great.

### CODE REVIEW

**Comment by ehg** [comment]
Thanks zzolo! I'm not going to merge this unfortunately; we use nginx to add JSONP callback support to both the sqlite API and static JSON files served over HTTP.

Does anyone else have any thoughts on this?

**Comment by zzolo** [comment]
Oh interesting.  Do you have info on how you accomplished that?  It sounds like a much efficient solution.

**Comment by tlevine** [comment]
We could change it to be an option, though, so that people can run this without special web-server configuration. And tests would be nice.

**Comment by ehg** [comment]
@zzolo we use nginx's lua module, I'll find the code for you tomorrow (I may need reminding)

@tlevine yeah, I saw thinking something similar.

**Comment by ehg** [comment]
@zzolo gist.github.com/746b2197f23f46eb3ea3

Hopefully we'll be open sourcing all our deployment stuff when we have time!

**Comment by zzolo** [comment]
Thanks for the link.  That's really helpful.

**Comment by pwaller** [comment]
Thanks for contributing. Apologies that this didn't make it in!

**Pull request closed without merging**
